name: "Wails Build Action"
description: "Creates a wails binary"

inputs:
  build:
    description: "Platform to build for"
    required: false
    default: "true"
  sign:
    description: "Sign the build"
    required: false
    default: "false"
  package:
    description: "Uploads workflow & uploads tag builds to a release"
    required: false
    default: "true"
  build-name:
    description: "The name of the binary file"
    required: true
  build-platform:
    description: "Platform to build for"
    required: false
    default: "darwin/universal"
  wails-version:
    description: "Wails version to use"
    required: false
    default: "latest"
  wails-build-webview2:
    description: "Webview2 installer method [download,embed,browser,error]"
    required: false
    default: "download"
  go-version:
    description: "Version of Go to use"
    required: false
    default: "1.17"
  node-version:
    description: "Node js version"
    required: false
    default: "16.x"
  deno-build:
    description: "This gets run into bash, use the full command"
    required: false
    default: ""
  deno-working-directory:
    description: "This gets run into bash, use the full command"
    required: false
    default: "."
  deno-version:
    description: "Deno version to use"
    required: false
    default: "v1.20.x"
  sign-macos-app-id:
    description: "MacOS Application Certificate id"
    required: false
    default: ''
  sign-macos-apple-password:
    description: "MacOS Apple password"
    required: false
    default: ''
  sign-macos-app-cert:
    description: "MacOS Application Certificate"
    required: false
    default: ''
  sign-macos-app-cert-password:
    description: "MacOS Application Certificate Password"
    required: false
    default: ''
  sign-macos-installer-id:
    description: "MacOS Installer Certificate id"
    required: false
    default: ''
  sign-macos-installer-cert:
    description: "MacOS Installer Certificate"
    required: false
    default: ''
  sign-macos-installer-cert-password:
    description: "MacOS Installer Certificate Password"
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # Setup and configure GoLang
    - name: Setup GoLang
      uses: actions/setup-go@v2
      with:
        go-version: ${{inputs.go-version}}
    - name: Setup Go Cache
      uses: actions/cache@v3
      with:
        path: |
          %LocalAppData%\go-build
          ~\go\pkg\mod
          ~/Library/Caches/go-build
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    # Setup and configure NodeJS
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: ${{inputs.node-version}}
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - name: Setup NodeJS cache
      uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    # (Optional) Setup and configure Deno
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      if: inputs.deno-build != ''
      with:
        deno-version: ${{inputs.deno-version}}
    - name: Setup Deno Cache
      uses: actions/cache@v3
      if: inputs.deno-build != ''
      with:
        path: |
          ~/.deno
          ~/.cache/deno
          ~/Library/Caches/deno
          ~\.deno
          %LocalAppData%\deno
        key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
    - name: Run Deno Command
      if: inputs.deno-build != ''
      shell: bash
      working-directory: ${{inputs.deno-working-directory}}
      run: ${{inputs.deno-build}}
    # install wails
    - name: Install Wails
      if: inputs.build == 'true'
      run: go install github.com/wailsapp/wails/v2/cmd/wails@${{inputs.wails-version}}
      shell: bash
    - name: Install Linux Wails deps
      if: inputs.build == 'true' && runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev
      shell: bash
    - name: Install macOS Wails deps
      if: inputs.sign == 'true' && runner.os == 'macOS'
      run: brew install mitchellh/gon/gon
      shell: bash
    # Building step
    - name: Build App
      if: inputs.build == 'true'
      run: wails build --platform ${{inputs.build-platform}} -webview2 ${{inputs.wails-build-webview2}}
      shell: bash
    - name: Add macOS perms
      if: inputs.build == 'true' && runner.os == 'macOS'
      run: chmod +x build/bin/*/Contents/MacOS/*
      shell: bash
    - name: Add Linux perms
      if: inputs.build == 'true' && runner.os  == 'Linux'
      run: chmod +x build/bin/*
      shell: bash
    # Package and Sign MacOS
    - name: Import Code-Signing Certificates for macOS
      if: runner.os == 'macOS' && inputs.sign == 'true' && startsWith(github.ref, 'refs/tags/')
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        keychain-password: ${{ inputs.sign-macos-apple-password }}
        p12-file-base64: ${{ inputs.sign-macos-app-cert }}
        p12-password: ${{ inputs.sign-macos-app-cert-password }}
    - name: Import Code-Signing Certificates for macOS Installer
      if: runner.os == 'macOS' && inputs.sign == 'true' && startsWith(github.ref, 'refs/tags/')
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        keychain-password: ${{ inputs.sign-macos-apple-password }}
        p12-file-base64: ${{ inputs.sign-macos-installer-cert }}
        p12-password: ${{ inputs.sign-macos-app-installer-password }}
        create-keychain: false
    - name: Sign our macOS binary
      if: runner.os == 'macOS' && inputs.sign == 'true' && startsWith(github.ref, 'refs/tags/')
      shell: bash
      env:
        APPLE_PASSWORD: ${{ inputs.sign-macos-apple-password }}
      run: |
        echo "Signing Package"
        gon -log-level=info ./build/darwin/gon-sign.json
    - name: Build .app zip file
      if: runner.os == 'macOS' && inputs.sign == 'true' && startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        ditto -c -k --keepParent ./build/bin/${{inputs.build-name}}.app ./build/bin/${{inputs.build-name}}.app.zip
    - name: Building Installer
      if: runner.os == 'macOS' && inputs.sign == 'true' && startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        productbuild --sign '${{inputs.sign-macos-installer-id}}' --component ./build/bin/${{inputs.build-name}}.app ./build/bin/${{inputs.build-name}}.pkg
    - name: Notarising Installer and zip
      if: runner.os == 'macOS' && inputs.sign == 'true' && startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        gon -log-level=info ./build/darwin/gon-notarize.json      

    # Upload build assets
    - uses: actions/upload-artifact@v2
      if: inputs.package == 'true'
      with:
        name: Wails ${{ runner.os }} Build
        path: |
          build/bin/
          build\bin\
    - name: Release
      uses: softprops/action-gh-release@v1
      if: inputs.package == 'true' && startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/bin/*
          build\bin\*